"""
generate_synthetic_data.py - Physically-Constrained Synthetic Demonstration Dataset Generator
SIH 2026 Problem Statement SIH26068

PROVENANCE POLICY:
All data generated by this module is explicitly categorized as:
"Synthetic / Demo Training Data — Not Real Observations"
Used solely to train and demonstrate the ML risk assessment architecture until
officially certified government disaster impact labels are integrated.
"""

import os
import numpy as np
import pandas as pd
from typing import Dict, Any, Tuple, List

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SYNTHETIC_DIR = os.path.join(BASE_DIR, "data", "synthetic")
PROCESSED_DIR = os.path.join(BASE_DIR, "data", "processed")

OUTPUT_SYNTHETIC_PATH = os.path.join(SYNTHETIC_DIR, "synthetic_weather_risk_demo.csv")
OUTPUT_ML_TRAIN_PATH = os.path.join(PROCESSED_DIR, "ml_training_dataset.csv")

# Regional anchors across India with climatological characteristics
REGIONS = [
    {"state": "Maharashtra", "district": "Nagpur", "lat": 21.1458, "lon": 79.0882, "climatology": 13.5},
    {"state": "Maharashtra", "district": "Wardha", "lat": 20.7453, "lon": 78.6022, "climatology": 12.0},
    {"state": "Uttar Pradesh", "district": "Lucknow", "lat": 26.8467, "lon": 80.9462, "climatology": 14.8},
    {"state": "Uttar Pradesh", "district": "Varanasi", "lat": 25.3176, "lon": 82.9739, "climatology": 15.2},
    {"state": "Uttar Pradesh", "district": "Gorakhpur", "lat": 26.7606, "lon": 83.3732, "climatology": 16.5},
    {"state": "Uttar Pradesh", "district": "Kanpur Nagar", "lat": 26.4499, "lon": 80.3319, "climatology": 13.2},
    {"state": "Odisha", "district": "Puri", "lat": 19.8135, "lon": 85.8312, "climatology": 18.0},
    {"state": "West Bengal", "district": "Kolkata", "lat": 22.5726, "lon": 88.3639, "climatology": 14.0},
    {"state": "Tamil Nadu", "district": "Chennai", "lat": 13.0827, "lon": 80.2707, "climatology": 24.5},
    {"state": "Gujarat", "district": "Ahmedabad", "lat": 23.0225, "lon": 72.5714, "climatology": 3.2},
    {"state": "Rajasthan", "district": "Jaipur", "lat": 26.9124, "lon": 75.7873, "climatology": 7.5},
    {"state": "Punjab", "district": "Ludhiana", "lat": 30.9010, "lon": 75.8573, "climatology": 22.0}
]

def calculate_physical_risk(row: Dict[str, Any]) -> Tuple[float, int, list]:
    """
    Computes a physically-grounded Weather Risk Score (0-100) and Risk Level (0-3).
    Evaluates multi-hazard interactions:
    - Extreme rainfall (> 64.5 mm / > 115 mm)
    - Prolonged multi-day cumulative precipitation
    - Extreme heat (>= 42°C) / Cold stress (<= 5°C)
    - Strong gale gusts (> 60 km/h)
    - Low atmospheric pressure depressions (< 990 hPa)
    - Saturated soil moisture (> 75%)
    - Above-normal rainfall anomaly
    """
    factors = []
    
    # 1. Rainfall Component (Weight: 40%)
    rain_1d = row["rainfall_1d"]
    rain_3d = row["rainfall_3d"]
    rain_7d = row["rainfall_7d"]
    anomaly = row["rainfall_anomaly"]
    
    rain_score = 0.0
    if rain_1d >= 115.6:  # IMD Very Heavy Rainfall
        rain_score = 100.0
        factors.append("Very heavy rainfall event (>115mm/24h)")
    elif rain_1d >= 64.5:  # IMD Heavy Rainfall
        rain_score = 75.0
        factors.append("Heavy rainfall (>64.5mm/24h)")
    elif rain_1d >= 35.5:  # Moderate-Heavy
        rain_score = 45.0
        factors.append("Moderate rainfall")
    elif rain_1d >= 15.0:
        rain_score = 25.0
    else:
        rain_score = min(rain_1d * 1.2, 20.0)
        
    # Multi-day saturation compounding
    if rain_3d >= 150.0:
        rain_score = min(rain_score + 25.0, 100.0)
        factors.append("Sustained 3-day severe rainfall accumulation")
    elif rain_7d >= 200.0:
        rain_score = min(rain_score + 15.0, 100.0)
        factors.append("Prolonged weekly high precipitation")
        
    if anomaly > 1.5 and rain_1d > 20.0:
        rain_score = min(rain_score + 15.0, 100.0)
        factors.append("High positive rainfall anomaly vs baseline")

    # 2. Wind Component (Weight: 25%)
    wind_gust = row["wind_gust"]
    wind_score = 0.0
    if wind_gust >= 75.0:
        wind_score = 100.0
        factors.append("Gale force wind gusts (>75 km/h)")
    elif wind_gust >= 55.0:
        wind_score = 70.0
        factors.append("Strong gusty winds (55-75 km/h)")
    elif wind_gust >= 38.0:
        wind_score = 40.0
        factors.append("Moderate wind activity")
    else:
        wind_score = min(wind_gust * 0.8, 20.0)

    # 3. Surface Pressure Depression (Weight: 15%)
    pressure = row["surface_pressure"]
    press_score = 0.0
    if pressure < 980.0:
        press_score = 100.0
        factors.append("Severe cyclonic barometric depression (<980 hPa)")
    elif pressure < 990.0:
        press_score = 70.0
        factors.append("Deep atmospheric pressure depression")
    elif pressure < 998.0:
        press_score = 35.0
    else:
        press_score = 5.0

    # 4. Temperature Extremes (Weight: 10%)
    t_max = row["temperature_max"]
    t_min = row["temperature_min"]
    temp_score = 0.0
    if t_max >= 45.0:
        temp_score = 100.0
        factors.append("Severe heatwave conditions (>=45°C)")
    elif t_max >= 42.0:
        temp_score = 70.0
        factors.append("Heatwave alert (>=42°C)")
    elif t_min <= 4.0:
        temp_score = 80.0
        factors.append("Severe cold wave warning (<=4°C)")
    elif t_min <= 7.0:
        temp_score = 50.0
        factors.append("Cold wave conditions (<=7°C)")
    else:
        temp_score = 10.0

    # 5. Soil Moisture Saturation (Weight: 10%)
    sm = row["soil_moisture"]
    soil_score = 0.0
    if sm >= 80.0 and rain_1d > 25.0:
        soil_score = 100.0
        factors.append("Saturated soil moisture with active rain (Flash flood/waterlogging risk)")
    elif sm >= 70.0:
        soil_score = 55.0
        factors.append("Elevated soil water saturation")
    elif sm <= 18.0 and t_max > 38.0:
        soil_score = 65.0
        factors.append("Severe soil moisture deficit / drought stress")
    else:
        soil_score = 10.0

    # Weighted Composite Risk Score
    composite_score = (
        0.40 * rain_score +
        0.25 * wind_score +
        0.15 * press_score +
        0.10 * temp_score +
        0.10 * soil_score
    )
    
    risk_score = float(np.round(np.clip(composite_score, 0.0, 100.0), 1))
    
    # Categorical Risk Level
    # 0 = LOW, 1 = MODERATE, 2 = HIGH, 3 = SEVERE
    if risk_score >= 75.0:
        risk_level = 3
    elif risk_score >= 50.0:
        risk_level = 2
    elif risk_score >= 25.0:
        risk_level = 1
    else:
        risk_level = 0
        
    return risk_score, risk_level, factors

def generate_synthetic_dataset(num_records: int = 12000, seed: int = 42) -> pd.DataFrame:
    """Generates physically correlated synthetic records matching all required features."""
    np.random.seed(seed)
    records = []
    start_date = pd.Timestamp("2023-01-01")
    
    for i in range(num_records):
        # Pick a regional anchor
        region = np.random.choice(REGIONS)
        # Random date over 2 years
        random_day = int(np.random.randint(0, 730))
        date = start_date + pd.Timedelta(days=random_day)
        month = date.month
        day_of_year = date.dayofyear
        
        # Season identification
        if month in [12, 1, 2]:
            season = "Winter"
            base_t = np.random.normal(18.0, 4.0)
            t_min = float(np.round(base_t - np.random.uniform(5.0, 10.0), 1))
            t_max = float(np.round(base_t + np.random.uniform(5.0, 11.0), 1))
            t_mean = float(np.round((t_min + t_max) / 2.0, 1))
            humidity_mean = float(np.round(np.random.uniform(45.0, 85.0), 1))
            humidity_max = float(np.round(min(humidity_mean + np.random.uniform(10.0, 20.0), 98.0), 1))
            pressure = float(np.round(np.random.normal(1014.0, 3.0), 1))
            wind_speed = float(np.round(np.random.uniform(4.0, 18.0), 1))
            wind_gust = float(np.round(wind_speed + np.random.uniform(4.0, 15.0), 1))
            # Low chance of winter rain
            has_rain = np.random.rand() < 0.12
            rain_1d = float(np.round(np.random.exponential(8.0), 1)) if has_rain else 0.0

        elif month in [3, 4, 5]:
            season = "Summer"
            base_t = np.random.normal(35.0, 4.0)
            t_min = float(np.round(base_t - np.random.uniform(6.0, 11.0), 1))
            t_max = float(np.round(base_t + np.random.uniform(5.0, 12.0), 1))
            t_mean = float(np.round((t_min + t_max) / 2.0, 1))
            humidity_mean = float(np.round(np.random.uniform(20.0, 50.0), 1))
            humidity_max = float(np.round(min(humidity_mean + np.random.uniform(10.0, 25.0), 75.0), 1))
            pressure = float(np.round(np.random.normal(1002.0, 4.0), 1))
            wind_speed = float(np.round(np.random.uniform(8.0, 28.0), 1))
            # Dust storms / pre-monsoon squalls
            has_squall = np.random.rand() < 0.08
            wind_gust = float(np.round(wind_speed + np.random.uniform(25.0, 55.0) if has_squall else wind_speed + np.random.uniform(5.0, 15.0), 1))
            has_rain = np.random.rand() < 0.15
            rain_1d = float(np.round(np.random.exponential(12.0), 1)) if has_rain else 0.0

        elif month in [6, 7, 8, 9]:
            season = "Monsoon"
            base_t = np.random.normal(29.0, 2.5)
            t_min = float(np.round(base_t - np.random.uniform(3.0, 6.0), 1))
            t_max = float(np.round(base_t + np.random.uniform(3.0, 8.0), 1))
            t_mean = float(np.round((t_min + t_max) / 2.0, 1))
            humidity_mean = float(np.round(np.random.uniform(70.0, 95.0), 1))
            humidity_max = float(np.round(min(humidity_mean + np.random.uniform(4.0, 10.0), 100.0), 1))
            pressure = float(np.round(np.random.normal(996.0, 5.0), 1))
            wind_speed = float(np.round(np.random.uniform(12.0, 35.0), 1))
            wind_gust = float(np.round(wind_speed + np.random.uniform(8.0, 30.0), 1))
            # Monsoon rain frequency is high (~65%)
            has_rain = np.random.rand() < 0.65
            if has_rain:
                # Pareto / heavy tail for monsoon downpours
                u = np.random.rand()
                if u > 0.96:
                    rain_1d = float(np.round(np.random.uniform(115.0, 220.0), 1))  # Extremely heavy
                elif u > 0.85:
                    rain_1d = float(np.round(np.random.uniform(65.0, 114.0), 1))   # Heavy
                elif u > 0.60:
                    rain_1d = float(np.round(np.random.uniform(25.0, 64.0), 1))    # Moderate
                else:
                    rain_1d = float(np.round(np.random.uniform(2.0, 24.0), 1))     # Light
            else:
                rain_1d = 0.0

        else:  # Post-Monsoon (Oct, Nov)
            season = "Post-Monsoon"
            base_t = np.random.normal(25.0, 3.5)
            t_min = float(np.round(base_t - np.random.uniform(5.0, 9.0), 1))
            t_max = float(np.round(base_t + np.random.uniform(4.0, 9.0), 1))
            t_mean = float(np.round((t_min + t_max) / 2.0, 1))
            humidity_mean = float(np.round(np.random.uniform(50.0, 75.0), 1))
            humidity_max = float(np.round(min(humidity_mean + np.random.uniform(8.0, 20.0), 92.0), 1))
            # Coastal cyclonic risk
            is_cyclone = np.random.rand() < 0.05
            if is_cyclone:
                pressure = float(np.round(np.random.uniform(970.0, 988.0), 1))
                wind_gust = float(np.round(np.random.uniform(65.0, 110.0), 1))
                wind_speed = float(np.round(wind_gust * 0.7, 1))
                rain_1d = float(np.round(np.random.uniform(70.0, 180.0), 1))
            else:
                pressure = float(np.round(np.random.normal(1010.0, 3.0), 1))
                wind_speed = float(np.round(np.random.uniform(6.0, 20.0), 1))
                wind_gust = float(np.round(wind_speed + np.random.uniform(4.0, 15.0), 1))
                rain_1d = float(np.round(np.random.exponential(10.0), 1)) if np.random.rand() < 0.20 else 0.0

        # Derived rolling rain features
        rain_3d = float(np.round(rain_1d + np.random.uniform(0.0, 2.2) * rain_1d, 1))
        rain_7d = float(np.round(rain_3d + np.random.uniform(0.0, 1.8) * rain_1d, 1))
        rain_30d = float(np.round(rain_7d + np.random.uniform(0.0, 2.5) * rain_1d, 1))
        
        # 24h changes
        t_change_24h = float(np.round(np.random.normal(0.0, 2.0), 1))
        rain_change_24h = float(np.round(rain_1d - np.random.uniform(0.0, rain_1d + 10.0), 1))
        
        # Climatology and anomaly
        climatology = float(region["climatology"])
        anomaly = float(np.round((rain_1d - climatology) / max(climatology, 0.01), 3))
        anomaly_pct = float(np.round(anomaly * 100.0, 1))
        
        # Soil moisture based on season and rain
        if season == "Monsoon":
            sm_base = 55.0
        elif season == "Summer":
            sm_base = 18.0
        else:
            sm_base = 32.0
            
        sm = float(np.round(np.clip(sm_base + (rain_7d * 0.25) - (t_mean * 0.2), 12.0, 92.0), 1))
        
        row_dict = {
            "date": date.strftime("%Y-%m-%d"),
            "state": region["state"],
            "district": region["district"],
            "latitude": region["lat"],
            "longitude": region["lon"],
            "month": month,
            "day_of_year": day_of_year,
            "season": season,
            "temperature_mean": t_mean,
            "temperature_max": t_max,
            "temperature_min": t_min,
            "humidity_mean": humidity_mean,
            "humidity_max": humidity_max,
            "wind_speed": wind_speed,
            "wind_gust": wind_gust,
            "surface_pressure": pressure,
            "precipitation": rain_1d,
            "rainfall_1d": rain_1d,
            "rainfall_3d": rain_3d,
            "rainfall_7d": rain_7d,
            "rainfall_30d": rain_30d,
            "rainfall_climatology": climatology,
            "rainfall_anomaly": anomaly,
            "rainfall_anomaly_percent": anomaly_pct,
            "temperature_change_24h": t_change_24h,
            "rainfall_change_24h": rain_change_24h,
            "soil_moisture": sm,
            "data_source": "Synthetic-Physics-Simulation",
            "is_real": False,
            "label_disclaimer": "Synthetic / Demo Training Data — Not Real Observations"
        }
        
        # Compute ground truth targets from documented physics simulation
        risk_score, risk_level, factors = calculate_physical_risk(row_dict)
        row_dict["risk_score"] = risk_score
        row_dict["weather_risk_level"] = risk_level
        row_dict["primary_risk_factors"] = "; ".join(factors[:3]) if factors else "Normal conditions"
        
        records.append(row_dict)
        
    df = pd.DataFrame(records)
    return df

def generate_and_save():
    os.makedirs(SYNTHETIC_DIR, exist_ok=True)
    os.makedirs(PROCESSED_DIR, exist_ok=True)
    
    print("[INFO] Generating 12,000 physically-correlated synthetic records...")
    synthetic_df = generate_synthetic_dataset(num_records=12000, seed=2026)
    
    synthetic_df.to_csv(OUTPUT_SYNTHETIC_PATH, index=False)
    print(f"[OK] Synthetic dataset saved to: {OUTPUT_SYNTHETIC_PATH}")
    print(f" -> Records: {len(synthetic_df)}")
    print(f" -> Risk level distribution:\n{synthetic_df['weather_risk_level'].value_counts(normalize=True).round(3)}")
    print(f" -> Risk score range: min={synthetic_df['risk_score'].min()}, max={synthetic_df['risk_score'].max()}, mean={synthetic_df['risk_score'].mean():.1f}")
    
    # Save the combined ML training dataset (features + target)
    synthetic_df.to_csv(OUTPUT_ML_TRAIN_PATH, index=False)
    print(f"[OK] ML Training dataset saved to: {OUTPUT_ML_TRAIN_PATH}")

if __name__ == "__main__":
    generate_and_save()
